version: '3.8'

services:
  frontend:
    build:
      context: ./mobile_front
      dockerfile: Dockerfile
    ports:
      - "8081:8081"   # Metro Bundler
      - "19000:19000" # Expo Go (Android)
      - "19001:19001" # Expo Go (iOS)
      - "19002:19002" # Expo Web
    depends_on:
      - backend
    volumes:
      - ./mobile_front:/usr/src/app
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npx expo start --tunnel

  backend:
    build:
      context: ./mobile_backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=dbpostgres

  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbpostgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
