name: CI - Front & Back

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ------------------------------------------------------------
  # Job : Backend (NestJS)
  # ------------------------------------------------------------
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies (Backend)
        run: |
          cd pocbackend
          npm install

      - name: Build (Backend)
        run: |
          cd pocbackend
          npm run build

      - name: Test (Backend)
        run: |
          cd pocbackend
          npm run test

  # ------------------------------------------------------------
  # Job : Frontend (React Native)
  # ------------------------------------------------------------
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies (Frontend)
        run: |
          cd POCMobile
          npm install

      - name: Test (Frontend)
        run: |
          cd POCMobile
          npm run test
